jobs:
  - job: Linux
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - task: CmdLine@2
        displayName: 'Run ./build.sh'
        inputs:
          script: |
            ./build.sh

  - job: macOS
    pool:
      vmImage: 'macOS-10.14'
    steps:
      # - task: CmdLine@2
      #   displayName: 'Install Mono 5.18'
      #   inputs:
      #     script: |
      #       curl -o ./mono.pkg https://download.mono-project.com/archive/5.18.0/macos-10-universal/MonoFramework-MDK-5.18.0.225.macos10.xamarin.universal.pkg
      #       sudo installer -verbose -pkg ./mono.pkg -target /

      - task: CmdLine@2
        displayName: 'Run ./build.sh'
        inputs:
          script: |
            ./build.sh

  - job: Windows
    pool:
      vmImage: 'windows-2019'
    steps:
      - task: CmdLine@2
        displayName: 'Run .\\build.ps1'
        inputs:
          script: |
            .\build.ps1
